#pragma once

#define WIZ_LOGIN				0x01
#define WIZ_NEW_CHAR			0x02
#define WIZ_DEL_CHAR			0x03
#define WIZ_SEL_CHAR			0x04
#define WIZ_SEL_NATION			0x05
#define WIZ_MOVE				0x06
#define WIZ_USER_INOUT			0x07
#define WIZ_ATTACK				0x08
#define WIZ_ROTATE				0x09
#define WIZ_NPC_INOUT			0x0A
#define WIZ_NPC_MOVE			0x0B
#define WIZ_ALLCHAR_INFO_REQ	0x0C
#define WIZ_GAMESTART			0x0D
#define WIZ_MYINFO				0x0E
#define WIZ_LOGOUT				0x0F
#define WIZ_CHAT				0x10
#define WIZ_DEAD				0x11
#define WIZ_REGENE				0x12
#define WIZ_TIME				0x13
#define WIZ_WEATHER				0x14
#define WIZ_REGIONCHANGE		0x15
#define WIZ_REQ_USERIN			0x16
#define WIZ_HP_CHANGE			0x17
#define WIZ_MSP_CHANGE			0x18
#define WIZ_NATION_CHAT			0x19
#define WIZ_EXP_CHANGE			0x1A
#define WIZ_LEVEL_CHANGE		0x1B
#define WIZ_NPC_REGION			0x1C
#define WIZ_REQ_NPCIN			0x1D
#define WIZ_WARP				0x1E
#define WIZ_ITEM_MOVE			0x1F
#define WIZ_NPC_EVENT			0x20
#define WIZ_ITEM_TRADE			0x21
#define WIZ_TARGET_HP			0x22
#define WIZ_ITEM_DROP			0x23
#define WIZ_BUNDLE_OPEN_REQ		0x24
#define WIZ_TRADE_NPC			0x25
#define WIZ_ITEM_GET			0x26
#define WIZ_ZONE_CHANGE			0x27
#define WIZ_POINT_CHANGE		0x28
#define WIZ_STATE_CHANGE		0x29
#define WIZ_LOYALTY_CHANGE		0x2A
#define WIZ_VERSION_CHECK		0x2B
#define WIZ_CRYPTION			0x2C
#define WIZ_USERLOOK_CHANGE		0x2D
#define WIZ_NOTICE				0x2E
#define WIZ_PARTY				0x2F
#define WIZ_EXCHANGE			0x30
#define WIZ_MAGIC_PROCESS		0x31
#define WIZ_SKILLPT_CHANGE		0x32
#define WIZ_OBJECT_EVENT		0x33
#define WIZ_CLASS_CHANGE		0x34
#define WIZ_CHAT_TARGET			0x35
#define WIZ_CONCURRENTUSER		0x36
#define WIZ_DATASAVE			0x37
#define WIZ_DURATION			0x38
#define WIZ_TIMENOTIFY			0x39
#define WIZ_REPAIR_NPC			0x3A
#define WIZ_ITEM_REPAIR			0x3B
#define WIZ_KNIGHTS_PROCESS		0x3C
#define WIZ_ITEM_COUNT_CHANGE   0x3D
#define WIZ_KNIGHTS_LIST		0x3E
#define WIZ_ITEM_REMOVE			0x3F
#define WIZ_OPERATOR			0x40
#define WIZ_SPEEDHACK_CHECK		0x41
#define WIZ_COMPRESS_PACKET		0x42
#define WIZ_SERVER_CHECK		0x43
#define WIZ_CONTINOUS_PACKET	0x44
#define WIZ_WAREHOUSE			0x45
#define WIZ_SERVER_CHANGE		0x46
#define WIZ_REPORT_BUG			0x47
#define WIZ_HOME				0x48
#define WIZ_FRIEND_PROCESS		0x49
#define WIZ_GOLD_CHANGE			0x4A
#define WIZ_WARP_LIST			0x4B
#define WIZ_VIRTUAL_SERVER		0x4C
#define WIZ_ZONE_CONCURRENT		0x4D
#define WIZ_CORPSE				0x4e
#define WIZ_PARTY_BBS			0x4f
#define WIZ_MARKET_BBS			0x50
#define WIZ_KICKOUT				0x51
#define WIZ_CLIENT_EVENT		0x52
#define WIZ_MAP_EVENT			0x53
#define WIZ_WEIGHT_CHANGE		0x54
#define WIZ_SELECT_MSG			0x55
#define WIZ_NPC_SAY				0x56
#define WIZ_BATTLE_EVENT		0x57
#define WIZ_AUTHORITY_CHANGE	0x58
#define WIZ_EDIT_BOX			0x59
#define WIZ_SANTA				0x5A
#define WIZ_ITEM_UPGRADE		0x5B
#define WIZ_CLAN_PREMIUM		0x5C
#define WIZ_PACKET2				0x5D
#define WIZ_ZONEABILITY			0x5E
#define WIZ_EVENT				0x5F
#define WIZ_STEALTH				0x60
#define WIZ_ROOM_PACKETPROCESS	0x61
#define WIZ_ROOM				0x62
#define WIZ_CLAN_BATTLE			0x63
#define WIZ_QUEST				0x64
#define WIZ_PP_CARD_LOGIN		0x65
#define WIZ_KISS				0x66
#define WIZ_RECOMMEND_USER		0x67
#define WIZ_MERCHANT			0x68
#define WIZ_MERCHANT_INOUT		0x69
#define WIZ_SHOPPING_MALL		0x6A
#define WIZ_SERVER_INDEX		0x6B
#define WIZ_EFFECT				0x6C
#define WIZ_SIEGE				0x6D
#define WIZ_NAME_CHANGE			0x6E
#define WIZ_WEBPAGE				0x6F
#define WIZ_CAPE				0x70
#define WIZ_PREMIUM				0x71
#define WIZ_HACKTOOL			0x72
#define WIZ_RENTAL				0x73
#define WIZ_ITEM_EXPIRATION		0x74
#define WIZ_CHALLENGE			0x75
#define WIZ_PET					0x76
#define WIZ_CHINA				0x77
#define WIZ_KING				0x78
#define WIZ_SKILLDATA			0x79
#define WIZ_PROGRAMCHECK		0x7A
#define WIZ_BIFROST				0x7B
#define WIZ_REPORT				0x7C
#define WIZ_LOGOSSHOUT			0x7D
#define WIZ_PACKET6				0x7E
#define WIZ_PACKET7				0x7F
#define WIZ_RANK				0x80
#define WIZ_STORY				0x81
#define WIZ_NATION_TRANSFER		0x82
#define WIZ_TERRAIN_EFFECTS		0x83
#define WIZ_MOVING_TOWER		0x84
#define WIZ_CAPTURE				0x85
#define WIZ_MINING				0x86
#define WIZ_HELMET				0x87
#define WIZ_PVP					0x88
#define WIZ_CHANGE_HAIR			0x89
#define WIZ_KAUL_A				0x8A
#define WIZ_VIPWAREHOUSE		0x8B
#define WIZ_KAUL_C				0x8C
#define WIZ_GENDER_CHANGE		0x8D
#define WIZ_PACKET16			0x8E
#define WIZ_PACKET17			0x8F
#define WIZ_LOYALTY_SHOP		0x90
#define WIZ_CLANPOINTS_BATTLE	0x91
#define WIZ_UTC_MOVIE			0x92
#define WIZ_GENIE				0x97
#define WIZ_USER_INFORMATIN  	0x98
#define WIZ_USER_ACHIEVE		0x99
#define WIZ_EXP_SEAL			0x9A
#define WIZ_KURIAN_SP_CHANGE	0x9B
#define WIZ_LOADING_LOGIN		0x9F
#define WIZ_HACKSHIELD_GUARD	0xA1
#define WIZ_TEST_PACKET			0xff
#define XIGNCODE3			    0xA0
#define RETURNE_BUFF_EXPIRE		0xA5
#define GATE_KEEPER_TAX			0xAC
#define WIZ_VANGUARD			0xB6
#define WIZ_KNIGHT_ROYALE		0xB7
#define WIZ_DB_DAILY_OP			0xD0
#define WIZ_DB_UPDATE_RANKING	0xD1
#define WIZ_DB_LOAD_RANKING		0xD2
#define WIZ_DB_DONATE_NP		0xD3
#define WIZ_RESET_LOYALTY		0xD4
#define WIZ_DB_NPOINTS			0xD5
#define XSafe_COM				0xF7
#define XSafe_AUTHINFO			0xB8
#define XSafe_PROCINFO			0xB9
#define XSafe_OPEN				0xBA
#define XSafe_LOG				0xBB
#define XSafe_ALIVE				0xBC
#define XSafe_UIINFO			0xBD
#define XSafe_PUS				0xBE
#define XSafe_CASHCHANGE		0xBF
#define WIZ_CAPTCHA				0xC0
#define XSafe_DROP_REQUEST		0xC1
#define XSafe_CR				0xC2
#define XSafe_CLANBANK			0xC3
#define XSafe_USERINFO			0xC4
#define XSafe_KCPAZAR			0xC5
#define XSafe_LOOT_SETTINS		0xC6
#define XSafe_CHAOTIC_EXCHANGE	0xC7
#define XSafe_CHAOTIC_RESULT	0xC8
#define XSafe_MERCHANT			0xC9
#define XSafe_USERDATA			0xCA
#define XSafe_TEMPITEMS			0xCB
#define XSafe_GMTOOLS			0xCC
#define XSafe_AUTODROP			0xCD
#define XSafe_SUPPORT			0xCE
#define XSafe_INFOMESSAGE		0xCF
#define XSafe_MERCHANTLIST		0xD6
#define XSafe_MESSAGE			0xD7
#define XSafe_LIFESKILL			0xD8
#define XSafe_HPINFO			0xD9
#define XSafe_MONSTER_INFO		0xDA
#define XSafe_EVENT				0xDB
#define XSafe_VOICE				0xDC
#define XSafe_PARTY_PROCESS		0xDD
#define LS_VERSION_REQ			0x01
#define LS_DOWNLOADINFO_REQ		0x02
#define LS_CRYPTION				0xF2
#define LS_LOGIN_REQ			0xF3
#define LS_MGAME_LOGIN			0xF4
#define LS_SERVERLIST			0xF5
#define LS_NEWS					0xF6
#define LS_UNKF7				0xF7
#define LS_OTP					0xFA
#define LS_OTP_SYNC				0xFD
#define NUM_LS_OPCODES			0xFF

const char* __stdcall opCode(unsigned char op);
//const char* __stdcall opCodeMagic(unsigned char subop);
//const char* __stdcall opCodeExchange(unsigned char subop);
//const char* __stdcall opCodeParty(unsigned char subop);
//const char* __stdcall opCodeWeather(unsigned char subop);
//const char* __stdcall opCodeChat(unsigned char subop);
//const char* __stdcall opCodeWarehouse(unsigned char subop);