#include "PacketsDefine.h"

const char* __stdcall opCode(unsigned char op)
{
	switch (op)
	{
	case WIZ_LOGIN:
		return "WIZ_LOGIN";
	case WIZ_NEW_CHAR:
		return "WIZ_NEW_CHAR";
	case WIZ_DEL_CHAR:
		return "WIZ_DEL_CHAR";
	case WIZ_SEL_CHAR:
		return "WIZ_SEL_CHAR";
	case WIZ_SEL_NATION:
		return "WIZ_SEL_NATION";
	case WIZ_MOVE:
		return "WIZ_MOVE";
	case WIZ_USER_INOUT:
		return "WIZ_USER_INOUT";
	case WIZ_ATTACK:
		return "WIZ_ATTACK";
	case WIZ_ROTATE:
		return "WIZ_ROTATE";
	case WIZ_NPC_INOUT:
		return "WIZ_NPC_INOUT";
	case WIZ_NPC_MOVE:
		return "WIZ_NPC_MOVE";
	case WIZ_ALLCHAR_INFO_REQ:
		return "WIZ_ALLCHAR_INFO_REQ";
	case WIZ_GAMESTART:
		return "WIZ_GAMESTART";
	case WIZ_MYINFO:
		return "WIZ_MYINFO";
	case WIZ_LOGOUT:
		return "WIZ_LOGOUT";
	case WIZ_CHAT:
		return "WIZ_CHAT";
	case WIZ_DEAD:
		return "WIZ_DEAD";
	case WIZ_REGENE:
		return "WIZ_REGENE";
	case WIZ_TIME:
		return "WIZ_TIME";
	case WIZ_WEATHER:
		return "WIZ_WEATHER";
	case WIZ_REGIONCHANGE:
		return "WIZ_REGIONCHANGE";
	case WIZ_REQ_USERIN:
		return "WIZ_REQ_USERIN";
	case WIZ_HP_CHANGE:
		return "WIZ_HP_CHANGE";
	case WIZ_MSP_CHANGE:
		return "WIZ_MSP_CHANGE";
	case WIZ_NATION_CHAT:
		return "WIZ_NATION_CHAT";
	case WIZ_EXP_CHANGE:
		return "WIZ_EXP_CHANGE";
	case WIZ_LEVEL_CHANGE:
		return "WIZ_LEVEL_CHANGE";
	case WIZ_NPC_REGION:
		return "WIZ_NPC_REGION";
	case WIZ_REQ_NPCIN:
		return "WIZ_REQ_NPCIN";
	case WIZ_WARP:
		return "WIZ_WARP";
	case WIZ_ITEM_MOVE:
		return "WIZ_ITEM_MOVE";
	case WIZ_NPC_EVENT:
		return "WIZ_NPC_EVENT";
	case WIZ_ITEM_TRADE:
		return "WIZ_ITEM_TRADE";
	case WIZ_TARGET_HP:
		return "WIZ_TARGET_HP";
	case WIZ_ITEM_DROP:
		return "WIZ_ITEM_DROP";
	case WIZ_BUNDLE_OPEN_REQ:
		return "WIZ_BUNDLE_OPEN_REQ";
	case WIZ_TRADE_NPC:
		return "WIZ_TRADE_NPC";
	case WIZ_ITEM_GET:
		return "WIZ_ITEM_GET";
	case WIZ_ZONE_CHANGE:
		return "WIZ_ZONE_CHANGE";
	case WIZ_POINT_CHANGE:
		return "WIZ_POINT_CHANGE";
	case WIZ_STATE_CHANGE:
		return "WIZ_STATE_CHANGE";
	case WIZ_LOYALTY_CHANGE:
		return "WIZ_LOYALTY_CHANGE";
	case WIZ_VERSION_CHECK:
		return "WIZ_VERSION_CHECK";
	case WIZ_CRYPTION:
		return "WIZ_CRYPTION";
	case WIZ_USERLOOK_CHANGE:
		return "WIZ_USERLOOK_CHANGE";
	case WIZ_NOTICE:
		return "WIZ_NOTICE";
	case WIZ_PARTY:
		return "WIZ_PARTY";
	case WIZ_EXCHANGE:
		return "WIZ_EXCHANGE";
	case WIZ_MAGIC_PROCESS:
		return "WIZ_MAGIC_PROCESS";
	case WIZ_SKILLPT_CHANGE:
		return "WIZ_SKILLPT_CHANGE";
	case WIZ_OBJECT_EVENT:
		return "WIZ_OBJECT_EVENT";
	case WIZ_CLASS_CHANGE:
		return "WIZ_CLASS_CHANGE";
	case WIZ_CHAT_TARGET:
		return "WIZ_CHAT_TARGET";
	case WIZ_CONCURRENTUSER:
		return "WIZ_CONCURRENTUSER";
	case WIZ_DATASAVE:
		return "WIZ_DATASAVE";
	case WIZ_DURATION:
		return "WIZ_DURATION";
	case WIZ_TIMENOTIFY:
		return "WIZ_TIMENOTIFY";
	case WIZ_REPAIR_NPC:
		return "WIZ_REPAIR_NPC";
	case WIZ_ITEM_REPAIR:
		return "WIZ_ITEM_REPAIR";
	case WIZ_KNIGHTS_PROCESS:
		return "WIZ_KNIGHTS_PROCESS";
	case WIZ_ITEM_COUNT_CHANGE:
		return "WIZ_ITEM_COUNT_CHANGE";
	case WIZ_KNIGHTS_LIST:
		return "WIZ_KNIGHTS_LIST";
	case WIZ_ITEM_REMOVE:
		return "WIZ_ITEM_REMOVE";
	case WIZ_OPERATOR:
		return "WIZ_OPERATOR";
	case WIZ_SPEEDHACK_CHECK:
		return "WIZ_SPEEDHACK_CHECK";
	case WIZ_COMPRESS_PACKET:
		return "WIZ_COMPRESS_PACKET";
	case WIZ_SERVER_CHECK:
		return "WIZ_SERVER_CHECK";
	case WIZ_CONTINOUS_PACKET:
		return "WIZ_CONTINOUS_PACKET";
	case WIZ_WAREHOUSE:
		return "WIZ_WAREHOUSE";
	case WIZ_SERVER_CHANGE:
		return "WIZ_SERVER_CHANGE";
	case WIZ_REPORT_BUG:
		return "WIZ_REPORT_BUG";
	case WIZ_HOME:
		return "WIZ_HOME";
	case WIZ_FRIEND_PROCESS:
		return "WIZ_FRIEND_PROCESS";
	case WIZ_GOLD_CHANGE:
		return "WIZ_GOLD_CHANGE";
	case WIZ_WARP_LIST:
		return "WIZ_WARP_LIST";
	case WIZ_VIRTUAL_SERVER:
		return "WIZ_VIRTUAL_SERVER";
	case WIZ_ZONE_CONCURRENT:
		return "WIZ_ZONE_CONCURRENT";
	case WIZ_CORPSE:
		return "WIZ_CORPSE";
	case WIZ_PARTY_BBS:
		return "WIZ_PARTY_BBS";
	case WIZ_MARKET_BBS:
		return "WIZ_MARKET_BBS";
	case WIZ_KICKOUT:
		return "WIZ_KICKOUT";
	case WIZ_CLIENT_EVENT:
		return "WIZ_CLIENT_EVENT";
	case WIZ_MAP_EVENT:
		return "WIZ_MAP_EVENT";
	case WIZ_WEIGHT_CHANGE:
		return "WIZ_WEIGHT_CHANGE";
	case WIZ_SELECT_MSG:
		return "WIZ_SELECT_MSG";
	case WIZ_NPC_SAY:
		return "WIZ_NPC_SAY";
	case WIZ_BATTLE_EVENT:
		return "WIZ_BATTLE_EVENT";
	case WIZ_AUTHORITY_CHANGE:
		return "WIZ_AUTHORITY_CHANGE";
	case WIZ_EDIT_BOX:
		return "WIZ_EDIT_BOX";
	case WIZ_SANTA:
		return "WIZ_SANTA";
	case WIZ_ITEM_UPGRADE:
		return "WIZ_ITEM_UPGRADE";
	case WIZ_CLAN_PREMIUM:
		return "WIZ_CLAN_PREMIUM";
	case WIZ_PACKET2:
		return "WIZ_PACKET2";
	case WIZ_ZONEABILITY:
		return "WIZ_ZONEABILITY";
	case WIZ_EVENT:
		return "WIZ_EVENT";
	case WIZ_STEALTH:
		return "WIZ_STEALTH";
	case WIZ_ROOM_PACKETPROCESS:
		return "WIZ_ROOM_PACKETPROCESS";
	case WIZ_ROOM:
		return "WIZ_ROOM";
	case WIZ_CLAN_BATTLE:
		return "WIZ_CLAN_BATTLE";
	case WIZ_QUEST:
		return "WIZ_QUEST";
	case WIZ_PP_CARD_LOGIN:
		return "WIZ_PP_CARD_LOGIN";
	case WIZ_KISS:
		return "WIZ_KISS";
	case WIZ_RECOMMEND_USER:
		return "WIZ_RECOMMEND_USER";
	case WIZ_MERCHANT:
		return "WIZ_MERCHANT";
	case WIZ_MERCHANT_INOUT:
		return "WIZ_MERCHANT_INOUT";
	case WIZ_SHOPPING_MALL:
		return "WIZ_SHOPPING_MALL";
	case WIZ_SERVER_INDEX:
		return "WIZ_SERVER_INDEX";
	case WIZ_EFFECT:
		return "WIZ_EFFECT";
	case WIZ_SIEGE:
		return "WIZ_SIEGE";
	case WIZ_NAME_CHANGE:
		return "WIZ_NAME_CHANGE";
	case WIZ_WEBPAGE:
		return "WIZ_WEBPAGE";
	case WIZ_CAPE:
		return "WIZ_CAPE";
	case WIZ_PREMIUM:
		return "WIZ_PREMIUM";
	case WIZ_HACKTOOL:
		return "WIZ_HACKTOOL";
	case WIZ_RENTAL:
		return "WIZ_RENTAL";
	case WIZ_ITEM_EXPIRATION:
		return "WIZ_ITEM_EXPIRATION";
	case WIZ_CHALLENGE:
		return "WIZ_CHALLENGE";
	case WIZ_PET:
		return "WIZ_PET";
	case WIZ_CHINA:
		return "WIZ_CHINA";
	case WIZ_KING:
		return "WIZ_KING";
	case WIZ_SKILLDATA:
		return "WIZ_SKILLDATA";
	case WIZ_PROGRAMCHECK:
		return "WIZ_PROGRAMCHECK";
	case WIZ_BIFROST:
		return "WIZ_BIFROST";
	case WIZ_REPORT:
		return "WIZ_REPORT";
	case WIZ_LOGOSSHOUT:
		return "WIZ_LOGOSSHOUT";
	case WIZ_PACKET6:
		return "WIZ_PACKET6";
	case WIZ_PACKET7:
		return "WIZ_PACKET7";
	case WIZ_RANK:
		return "WIZ_RANK";
	case WIZ_STORY:
		return "WIZ_STORY";
	case WIZ_NATION_TRANSFER:
		return "WIZ_NATION_TRANSFER";
	case WIZ_TERRAIN_EFFECTS:
		return "WIZ_TERRAIN_EFFECTS";
	case WIZ_MOVING_TOWER:
		return "WIZ_MOVING_TOWER";
	case WIZ_CAPTURE:
		return "WIZ_CAPTURE";
	case WIZ_MINING:
		return "WIZ_MINING";
	case WIZ_HELMET:
		return "WIZ_HELMET";
	case WIZ_PVP:
		return "WIZ_PVP";
	case WIZ_CHANGE_HAIR:
		return "WIZ_CHANGE_HAIR";
	case WIZ_KAUL_A:
		return "WIZ_KAUL_A";
	case WIZ_VIPWAREHOUSE:
		return "WIZ_VIPWAREHOUSE";
	case WIZ_KAUL_C:
		return "WIZ_KAUL_C";
	case WIZ_GENDER_CHANGE:
		return "WIZ_GENDER_CHANGE";
	case WIZ_PACKET16:
		return "WIZ_PACKET16";
	case WIZ_PACKET17:
		return "WIZ_PACKET17";
	case WIZ_LOYALTY_SHOP:
		return "WIZ_LOYALTY_SHOP";
	case WIZ_CLANPOINTS_BATTLE:
		return "WIZ_CLANPOINTS_BATTLE";
	case WIZ_UTC_MOVIE:
		return "WIZ_UTC_MOVIE";
	case WIZ_GENIE:
		return "WIZ_GENIE";
	case WIZ_USER_INFORMATIN:
		return "WIZ_USER_INFORMATIN";
	case WIZ_USER_ACHIEVE:
		return "WIZ_USER_ACHIEVE";
	case WIZ_EXP_SEAL:
		return "WIZ_EXP_SEAL";
	case WIZ_KURIAN_SP_CHANGE:
		return "WIZ_KURIAN_SP_CHANGE";
	case WIZ_LOADING_LOGIN:
		return "WIZ_LOADING_LOGIN";
	case WIZ_HACKSHIELD_GUARD:
		return "WIZ_HACKSHIELD_GUARD";
	case WIZ_TEST_PACKET:
		return "WIZ_TEST_PACKET";
	case XIGNCODE3:
		return "XIGNCODE3";
	case RETURNE_BUFF_EXPIRE:
		return "RETURNE_BUFF_EXPIRE";
	case GATE_KEEPER_TAX:
		return "GATE_KEEPER_TAX";
	case WIZ_VANGUARD:
		return "WIZ_VANGUARD";
	case WIZ_KNIGHT_ROYALE:
		return "WIZ_KNIGHT_ROYALE";
	case WIZ_DB_DAILY_OP:
		return "WIZ_DB_DAILY_OP";
	case WIZ_DB_UPDATE_RANKING:
		return "WIZ_DB_UPDATE_RANKING";
	case WIZ_DB_LOAD_RANKING:
		return "WIZ_DB_LOAD_RANKING";
	case WIZ_DB_DONATE_NP:
		return "WIZ_DB_DONATE_NP";
	case WIZ_RESET_LOYALTY:
		return "WIZ_RESET_LOYALTY";
	case WIZ_DB_NPOINTS:
		return "WIZ_DB_NPOINTS";
	case XSafe_COM:
		return "XSafe_COM";
	case XSafe_AUTHINFO:
		return "XSafe_AUTHINFO";
	case XSafe_PROCINFO:
		return "XSafe_PROCINFO";
	case XSafe_OPEN:
		return "XSafe_OPEN";
	case XSafe_LOG:
		return "XSafe_LOG";
	case XSafe_ALIVE:
		return "XSafe_ALIVE";
	case XSafe_UIINFO:
		return "XSafe_UIINFO";
	case XSafe_PUS:
		return "XSafe_PUS";
	case XSafe_CASHCHANGE:
		return "XSafe_CASHCHANGE";
	case WIZ_CAPTCHA:
		return "WIZ_CAPTCHA";
	case XSafe_DROP_REQUEST:
		return "XSafe_DROP_REQUEST";
	case XSafe_CR:
		return "XSafe_CR";
	case XSafe_CLANBANK:
		return "XSafe_CLANBANK";
	case XSafe_USERINFO:
		return "XSafe_USERINFO";
	case XSafe_KCPAZAR:
		return "XSafe_KCPAZAR";
	case XSafe_LOOT_SETTINS:
		return "XSafe_LOOT_SETTINS";
	case XSafe_CHAOTIC_EXCHANGE:
		return "XSafe_CHAOTIC_EXCHANGE";
	case XSafe_CHAOTIC_RESULT:
		return "XSafe_CHAOTIC_RESULT";
	case XSafe_MERCHANT:
		return "XSafe_MERCHANT";
	case XSafe_USERDATA:
		return "XSafe_USERDATA";
	case XSafe_TEMPITEMS:
		return "XSafe_TEMPITEMS";
	case XSafe_GMTOOLS:
		return "XSafe_GMTOOLS";
	case XSafe_AUTODROP:
		return "XSafe_AUTODROP";
	case XSafe_SUPPORT:
		return "XSafe_SUPPORT";
	case XSafe_INFOMESSAGE:
		return "XSafe_INFOMESSAGE";
	case XSafe_MERCHANTLIST:
		return "XSafe_MERCHANTLIST";
	case XSafe_MESSAGE:
		return "XSafe_MESSAGE";
	case XSafe_LIFESKILL:
		return "XSafe_LIFESKILL";
	case XSafe_HPINFO:
		return "XSafe_HPINFO";
	case XSafe_MONSTER_INFO:
		return "XSafe_MONSTER_INFO";
	case XSafe_EVENT:
		return "XSafe_EVENT";
	case XSafe_VOICE:
		return "XSafe_VOICE";
	case XSafe_PARTY_PROCESS:
		return "XSafe_PARTY_PROCESS";
	default:
		return "?Unknown?OpCode?";
	}
}
